In [ ]:
#Import necessary modules and libraries
import numpy as np
import random

In [ ]:
#Exercise 4.1
#Problem 1
#1)
empty_array = np.empty((2,2))
print(empty_array)

[[5.04718493e-310 0.00000000e+000]
 [6.54067889e-310 6.54069996e-310]]


In [ ]:
#2)
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3)
ones_array.fill(4)
print(ones_array)

[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


In [ ]:
#4)
zeros_like = np.zeros_like(ones_array)
zeros_like

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
#5)
a = np.arange(1,10)
b = a.reshape(3,3)
print(b)
ones_like = np.ones_like(b)
print(ones_like)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:

#6)
new_list = [1,2,3,4]
print(new_list)
new_array = np.array(new_list)
new_array

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [ ]:
#Import necessary modules and libraries
import numpy as np
import random

In [5]:
#Exercise 4.1.1
#Problem 1
#1
empty_array = np.empty((2,2))
print(empty_array)


[[4.94268028e-310 0.00000000e+000]
 [4.94065646e-324 6.94268930e-310]]


In [6]:
#2)
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
#3)
ones_array.fill(4)
print(ones_array)

[[4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]]


In [8]:
#4)
zeros_like = np.zeros_like(ones_array)
zeros_like

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
#5)
a = np.arange(1,10)
b = a.reshape(3,3)
print(b)
ones_like = np.ones_like(b)
print(ones_like)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
#6)
new_list = [1,2,3,4]
print(new_list)
new_array = np.array(new_list)
new_array

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [11]:
#Problem 2
#1)
array_range = np.arange(10, 49)
array_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [12]:
#2)
array_linspace = np.linspace(0,8, endpoint = True, num = 9)
array_linspace.reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [13]:
#3)
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
#4)
random_array = np.random.randint(0,30, size = 30)
random_array
array_mean = np.mean(random_array)
array_mean

12.366666666666667

In [15]:
#5)
random_array_1 = np.random.randint(0, 50, size = (10,10))
random_array_1
print("The maximum value is: ", np.max(random_array_1))
print("The minimum value is: ", np.min(random_array_1))

The maximum value is:  49
The minimum value is:  0


In [16]:
#6)
zero_array = np.zeros(5)
zero_array
zero_array[4] = 1
zero_array

array([0., 0., 0., 0., 1.])

In [17]:
#7
arr = [1,2,0,0,4,0]
arr1 = np.array(arr)
reversed = np.flip(arr1)
reversed

array([0, 4, 0, 0, 2, 1])

In [18]:
#8)
two_d_array = np.array([[2,3,4], [2,3,4]])
two_d_array[0:2, 0:3:2] = 1
two_d_array[0:2, 1:3:2] = 0
two_d_array

array([[1, 0, 1],
       [1, 0, 1]])

In [19]:
#9)
eight_d_array = np.zeros((8,8))

eight_d_array[::2, ::2] = 1
eight_d_array[1::2, 1::2] = 1
eight_d_array

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [20]:
#Problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);
#1)
print(x+y, v+w)

[[ 6  8]
 [10 13]] [20 22]


In [21]:
#2)
print(x-y, v-w)

[[-4 -4]
 [-4 -3]] [-2 -2]


In [22]:
#3)
print(x*3, v*4)

[[ 3  6]
 [ 9 15]] [36 40]


In [23]:
#4)
print(x ** 2, v ** 2)

[[ 1  4]
 [ 9 25]] [ 81 100]


In [24]:
#5)
print("The dot product of x and y is: ",np.dot(x,y), sep = '\n\n')
print("The dot product of x and v is: ",np.dot(x,v), sep = '\n\n')
print("The dot product of v and w is: ",np.dot(v,w), sep = '\n\n')

The dot product of x and y is: 

[[19 22]
 [50 58]]
The dot product of x and v is: 

[29 77]
The dot product of v and w is: 

219


In [25]:
#6)
#Concatenation of matrices
print("The concatenation along row axis: ", np.concatenate((x,y), axis = 0))
print("The concatenation along column axis: ",np.concatenate((x,y), axis = 1))

The concatenation along row axis:  [[1 2]
 [3 5]
 [5 6]
 [7 8]]
The concatenation along column axis:  [[1 2 5 6]
 [3 5 7 8]]


In [40]:
import numpy as np

# Example arrays
x = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])

# Concatenating along axis 1 (horizontally)
result = np.concatenate((x, v), axis=1)

print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#7)
np.concatenate((x,v), axis = 0)

In [29]:
#Problem 4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [30]:
#A.A−1 = I
np.matmul(A, np.linalg.inv(A))

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [31]:
A @ np.linalg.inv(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [32]:
#AB ̸= BA
AB = A @ B
BA = B @ A
AB == BA

array([[False, False],
       [False, False]])

In [33]:
# (AB)T = BTAT
AB_T = np.transpose(AB)
BA_T = np.transpose(B) @ np.transpose(A)
AB_T == BA_T

array([[ True,  True],
       [ True,  True]])

In [34]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
X = np.linalg.solve(A,B)
X

array([ 2.,  1., -2.])

In [35]:
#Using Inverse Method
A_inv = np.linalg.inv(A)
X = A_inv @ B
X

array([ 2.,  1., -2.])

In [38]:
import random
import numpy as np
from timeit import timeit

# Seed for reproducibility
random.seed(0)

# Element-wise Addition
A = [random.randint(0, 100) for _ in range(1000000)]
B = [random.randint(0, 100) for _ in range(1000000)]
Aa = np.array(A)
Bb = np.array(B)

def add_python(X, Y):
    return [x + y for x, y in zip(X, Y)]

def add_numpy(X, Y):
    return np.add(X, Y)

# Timing the functions
python_time = timeit(lambda: add_python(A, B), number=1000)
numpy_time = timeit(lambda: add_numpy(Aa, Bb), number=1000)

print(f"The time taken to python is: {python_time:.6f}")
print(f"The time taken to numpy is: {numpy_time:.6f}")


The time taken to python is: 74.583420
The time taken to numpy is: 1.843705


In [41]:
#Element-wise Multiplication
def multiply_python(X, Y):
    return [x * y for x, y in zip(X, Y)]
def multiply_numpy(X, Y):
    return np.multiply(X, Y)
python_time = timeit(lambda: multiply_python(A, B), number = 1000)
numpy_time = timeit(lambda: multiply_numpy(Aa, Bb), number = 1000)
print(f"The time taken to python is: {python_time:.6f}")
print(f"The time taken to numpy is: {numpy_time:.6f}")

The time taken to python is: 96.127832
The time taken to numpy is: 1.894428


In [ ]:
#Dot Product
def dot_python(X, Y):
    return sum(x * y for x, y in zip(X, Y))
def dot_numpy(X, Y):
    return np.dot(X, Y)
python_time = timeit(lambda: dot_python(A, B), number = 1000)
numpy_time = timeit(lambda: dot_numpy(Aa, Bb), number = 1000)

In [ ]:
import random
import numpy as np
from timeit import timeit

m, n, p = 100, 200, 150

A = [[random.randint(0, 100) for _ in range(n)] for _ in range(m)]
B = [[random.randint(0, 100) for _ in range(p)] for _ in range(n)]
Aa = np.array(A)
Bb = np.array(B)

def matrix_multiply_python(X, Y):
    result = [[0 for _ in range(len(Y[0]))] for _ in range(len(X))]
    for i in range(len(X)):
        for j in range(len(Y[0])):
            for k in range(len(Y)):
                result[i][j] += X[i][k] * Y[k][j]
    return result

def matrix_multiply_numpy(X, Y):
    return np.matmul(X, Y)

python_time = timeit(lambda: matrix_multiply_python(A, B), number=100)
numpy_time = timeit(lambda: matrix_multiply_numpy(Aa, Bb), number=100)

print(f"The time taken to multiply using Python is: {python_time:.6f} seconds")
print(f"The time taken to multiply using Numpy is: {numpy_time:.6f} seconds")
